### PR TITLE
Blocking waits

### PR DESCRIPTION
**Pull request by roel-de-regt**
Adds blocking waits to allow use in both asynchronous and synchronous projects.

# Description of changes in this pull request

I'm using the keyed-semaphore assembly in new projects that are fully asynchronous, but I also want to use it in my existing legacy code base which is synchronous. By adding a few blocking wait methods, I can now do so without having to worry about the nasty things that happen when you mix asynchronous and synchronous code.

# Public API Changes
The IKeyedSemaphore interface is extended with Wait methods that mirror the existing WaitAsync methods.
The KeyedSemaphore interface is extended with a Lock method that mirrors the existing LockAsync method.

### CODE REVIEW

**Comment by amoerie** [comment]
Hi Roel, thanks for your contribution! 

I'm not against adding these methods, but I do want to discourage their use. These wait methods essentially block the current thread synchronously, introducing the risk of deadlocks if care is not taken. In new projects, these shouldn't be used.
That's why I would suggest to immediately mark these methods as [Obsolete], with a message that explains that the method only exists for backwards compatibility in legacy projects (your use case, essentially) and that the asynchronous counterparts are preferred if possible.

Secondly, while I can see that you have written very "unrisky" code (you mostly delegate to SemaphoreSlim.Wait), I still feel uncomfortable adding untested code. I would like to see a similar set of tests to cover the new synchronous methods. 

This will probably involve making a copy of some of the existing tests and then refactoring them to use Thread instead of Task. If you need any pointers or assistance, I could help with this.

**Comment by roel-de-regt** [comment]
Hi Alexander,

I understand your concerns about the use of synchronous methods, but for me
it is the other way around and I have the same concerns about asynchronous
methods. I'm responsible for maintaining a codebase of over a million lines
of synchronous code. Developers carelessly inserting asynchronous calls
within this code are a major headache as this can result in difficult to
diagnose deadlocks.

We're using the keyed semaphores in a project that consists of an
asynchronous API and background tasks still running synchronously. The fact
that the keyed semaphores can operate in both environments is a major
benefit and solves a lot of headaches.

I don't think adding new methods to the library, immediately marking them
as obsolete is a good way forward for us or your library. If you want to
keep it clean and consistent, which I understand, I will use our cloned
copy in our private code base - because for us it is a very useful tool.

Best regards,
Roel de Regt

**Comment by amoerie** [comment]
Hi @roel-de-regt 

Thanks for getting back to me. I understand your situation, and I can imagine a lot of people are in it. 

From my own experience, it's inconvenient to keep private copies around of open source software. 
Future fixes from the open source community need to be merged manually (if someone cares enough to take the time at all) and worse, corporate fixes rarely make it back to open source.

In the interest of making both of our lives easier, I am willing to add the new synchronous APIs without marking them as obsolete, but only with a comment saying that the asynchronous APIs are preferred because they don't block.

I still want to see some tests for the sync APIs though. :-) But if you need help with those, please let me know. I don't want this to be an obstacle for you.

**Comment by amoerie** [comment]
I decided to fill in the missing tests myself, thanks for the contribution!

**Pull request merged**
